#!/usr/bin/env python3
"""Generate the fixed native target-slab chunk contract from its manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ARTIFACT_KEY = "a9fcca026a87ad1285b94feef19448c51b42d97516f16211c61ae4c770c6f0f4"
MANIFEST_SHA256 = "a44a450d9c0b6fe3df904ad1a78ecee959f28d9f055301195181e986bdc7028b"


def canonical(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode()


def generate(artifact: Path) -> str:
    manifest_path = artifact / "manifest.json"
    raw = manifest_path.read_bytes()
    manifest = json.loads(raw)
    digest_input = dict(manifest)
    claimed = digest_input.pop("artifact_key", None)
    if (
        artifact.name != ARTIFACT_KEY
        or claimed != ARTIFACT_KEY
        or hashlib.sha256(canonical(digest_input)).hexdigest() != ARTIFACT_KEY
        or hashlib.sha256(raw).hexdigest() != MANIFEST_SHA256
    ):
        raise ValueError("authenticated target-slab manifest changed")
    lines = ["// Generated by qwen38-generate-native-target-slab-contract.py."]
    for rank in (0, 1):
        slab = manifest["slabs"][f"rank{rank}-target"]
        selected = {key: slab[key] for key in ("file", "bytes", "chunks")}
        layout = hashlib.sha256(canonical(selected)).hexdigest()
        chunks = slab["chunks"]
        if slab["bytes"] != 63_212_748_800 or len(chunks) != 236:
            raise ValueError("target-slab extent changed")
        lines.extend([
            f'inline constexpr std::string_view kRank{rank}LayoutSha256 = "{layout}";',
            f"inline constexpr std::array<TargetSlabChunk, 236> kRank{rank}Chunks{{{{",
        ])
        expected_offset = 0
        for item in chunks:
            if item["offset_bytes"] != expected_offset:
                raise ValueError("target-slab chunk order changed")
            expected_offset += item["length_bytes"]
            lines.append(
                "    {%dULL, %dULL, \"%s\"},"
                % (item["offset_bytes"], item["length_bytes"], item["sha256"])
            )
        if expected_offset != slab["bytes"]:
            raise ValueError("target-slab chunks do not cover payload")
        lines.append("}};")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(generate(args.artifact), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
