// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <stdexcept>
#include <string>
#include <string_view>

namespace rocket::qwen38::mtp {

inline constexpr int kNcclWorldSize = 2;
inline constexpr int kPinnedNcclRawVersion = 23'007;
inline constexpr std::size_t kNcclUniqueIdBytes = 128;

enum class NcclBootstrapStage : std::uint8_t {
  kValidate,
  kLoad,
  kConnect,
  kAuthenticate,
  kBindDevice,
  kInitialize,
  kVerify,
  kReady,
  kTeardown,
};

enum class NcclBootstrapOutcome : std::uint8_t {
  kOk,
  kContractError,
  kLibraryError,
  kTransportError,
  kAuthenticationError,
  kCudaError,
  kNcclError,
};

constexpr std::string_view stage_name(NcclBootstrapStage stage) noexcept {
  switch (stage) {
    case NcclBootstrapStage::kValidate: return "validate";
    case NcclBootstrapStage::kLoad: return "load";
    case NcclBootstrapStage::kConnect: return "connect";
    case NcclBootstrapStage::kAuthenticate: return "authenticate";
    case NcclBootstrapStage::kBindDevice: return "bind_device";
    case NcclBootstrapStage::kInitialize: return "initialize";
    case NcclBootstrapStage::kVerify: return "verify";
    case NcclBootstrapStage::kReady: return "ready";
    case NcclBootstrapStage::kTeardown: return "teardown";
  }
  return "validate";
}

constexpr std::string_view outcome_name(NcclBootstrapOutcome outcome) noexcept {
  switch (outcome) {
    case NcclBootstrapOutcome::kOk: return "ok";
    case NcclBootstrapOutcome::kContractError: return "contract_error";
    case NcclBootstrapOutcome::kLibraryError: return "library_error";
    case NcclBootstrapOutcome::kTransportError: return "transport_error";
    case NcclBootstrapOutcome::kAuthenticationError:
      return "authentication_error";
    case NcclBootstrapOutcome::kCudaError: return "cuda_error";
    case NcclBootstrapOutcome::kNcclError: return "nccl_error";
  }
  return "contract_error";
}

class NcclBootstrapError : public std::runtime_error {
 public:
  using std::runtime_error::runtime_error;
};
class NcclBootstrapContractError final : public NcclBootstrapError {
 public:
  using NcclBootstrapError::NcclBootstrapError;
};
class NcclBootstrapLibraryError final : public NcclBootstrapError {
 public:
  using NcclBootstrapError::NcclBootstrapError;
};
class NcclBootstrapTransportError final : public NcclBootstrapError {
 public:
  using NcclBootstrapError::NcclBootstrapError;
};
class NcclBootstrapAuthenticationError final : public NcclBootstrapError {
 public:
  using NcclBootstrapError::NcclBootstrapError;
};
class NcclBootstrapCudaError final : public NcclBootstrapError {
 public:
  using NcclBootstrapError::NcclBootstrapError;
};
class NcclBootstrapNcclError final : public NcclBootstrapError {
 public:
  using NcclBootstrapError::NcclBootstrapError;
};

// OpenTelemetry adapter boundary supplied by the embedding process. Attribute
// cardinality is closed: stage has nine values, outcome has seven, rank has
// {-1,0,1}, and world_size is always two. Host, ports, session material,
// library paths, NCCL diagnostics, and durations are never attributes.
struct NcclBootstrapTelemetryRecord {
  NcclBootstrapStage stage;
  NcclBootstrapOutcome outcome;
  int rank;
  int world_size;
  std::uint64_t duration_ns;
};

class NcclBootstrapOtelSink {
 public:
  virtual ~NcclBootstrapOtelSink() = default;
  virtual void emit_span_and_log(
      const NcclBootstrapTelemetryRecord& record) noexcept = 0;
  virtual void record_duration(
      const NcclBootstrapTelemetryRecord& record) noexcept = 0;
};

struct NcclCommunicatorConfig {
  int rank = -1;
  int peer_rank = -1;
  int device = -1;
  std::string bootstrap_host;
  int bootstrap_port = 0;
  int pair_reduce_bootstrap_port = 0;
  std::uint32_t timeout_ms = 0;
  // The stable per-invocation identity authenticated on the wire.
  std::array<std::uint8_t, 32> session_sha256{};
  // An independent ephemeral 256-bit key generated by the supervisor. It is
  // retained only in memory for construction and is never sent or exposed to
  // telemetry. The caller owns generation, storage, rotation, and destruction.
  std::array<std::uint8_t, 32> authentication_key{};
  std::string nccl_library = "libnccl.so.2";
  std::string cuda_runtime_library = "libcudart.so.13";
};

// Owns one NCCL communicator for exactly two ranks on process-local CUDA device
// zero. Construction performs bounded authenticated metadata exchange over its
// dedicated TCP port, then enters blocking ncclCommInitRank concurrently on both
// ranks and validates count, user rank, and async state. TCP operations are each
// bounded by timeout_ms; NCCL's blocking initialization has NCCL's own transport
// timeout contract. Success transfers no ownership to callers. destroy is used
// for normal teardown; abort is used after partial initialization or async fault.
//
// Lifecycle follows vLLM 8e685d198 PyNcclCommunicator: rank zero alone mints the
// 128-byte ID, metadata travels outside NCCL, device binding precedes init, and
// communicator teardown is explicit. This owner removes vLLM's general process
// group and specializes the contract to Rocket's fixed TP2/CUDA0 deployment.
// The telemetry sink is borrowed and must outlive the owner. The type is
// single-owner, non-copyable, non-movable, and not thread-safe.
class NcclCommunicatorOwner final {
 public:
  NcclCommunicatorOwner(const NcclCommunicatorConfig& config,
                        NcclBootstrapOtelSink& telemetry);
  ~NcclCommunicatorOwner();
  NcclCommunicatorOwner(const NcclCommunicatorOwner&) = delete;
  NcclCommunicatorOwner& operator=(const NcclCommunicatorOwner&) = delete;
  NcclCommunicatorOwner(NcclCommunicatorOwner&&) = delete;
  NcclCommunicatorOwner& operator=(NcclCommunicatorOwner&&) = delete;

  [[nodiscard]] void* communicator() const noexcept;
  [[nodiscard]] int rank() const noexcept;
  [[nodiscard]] int world_size() const noexcept { return kNcclWorldSize; }
  [[nodiscard]] std::string_view nccl_library_path() const noexcept;

  void validate_async();
  void abort() noexcept;
  static void validate_config(const NcclCommunicatorConfig& config);

 private:
  struct Impl;
  std::unique_ptr<Impl> impl_;
};

}  // namespace rocket::qwen38::mtp
